expresstrade/cart/urls.py
from django.conf.urls import url

from .views import (
    cart_home
)

urlpatterns = [
    # name='detail' can be used as a shortcut to get here
    url(r'^$', cart_home, name='cart'),

]

expresstrade/expresstrade/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

from .views import home_page, contact_page, login_page, register_page, logout_page

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_page, name='home'),
    url(r'^logout/$', logout_page, name='logout'),
    url(r'^contact/', contact_page, name='contact'),
    url(r'^login/$', login_page, name='login'),
    url(r'^register/$', register_page, name='register'),
    url(r'^products/', include("products.urls", namespace="products")),
    url(r'^search/', include("searchbox.urls", namespace="search")),
    url(r'^cart/', include("cart.urls", namespace="cart"))

]
# Media files are all whatever we upload ourselves
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# OLD VERSION

# from products.views import (
#     ProductListView,
#     ProductDetailView,
#     ProductDetailSlugView,
#     ProductFeaturedDetailView,
#     ProductFeaturedListView)

# URLS

# url(r'^products/$', ProductListView.as_view()),
# url(r'^products/(?P<pk>\d+)/$', ProductDetailView.as_view()),
# url(r'^products/(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view()),
# url(r'^featured/$', ProductFeaturedListView.as_view()),
# url(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view()),

expresstrade/products/urls.py
from django.conf.urls import url

from .views import (
    ProductListView,
    ProductDetailSlugView,
)

urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='list'),
    # name='detail' can be used as a shortcut to get here
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),

]

# NOT USED URLS FOR TESTING

# from .views import (
# ProductDetailView,
# ProductFeaturedDetailView,
# ProductFeaturedListView
# )

# url(r'^featured/$', ProductFeaturedListView.as_view()),
# url(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view()),
# url(r'^products/(?P<pk>\d+)/$', ProductDetailView.as_view()),

expresstrade/templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css"
      integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">

<link rel="stylesheet" href='{% static "css/main.css" %}'>

<!-- Custom styles for this template -->
{#    <link href="{% static "css/main.css" %}" rel="stylesheet">#}

{#static_root/css/#}

expresstrade/templates/base/footer.html
<!-- FOOTER -->
{% url 'contact' as contact_url %}
<div class="container-fluid footer navbar-fixed-bottom">
    <br>
    <br>
    <br>
    <footer>
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>Copyright &copy; Sergiusz Wójcik, 2018 Inc. &middot; <a href="{{ contact_url }}">Contact  </a>&middot;
            <a href="#">Privacy  </a> &middot; <a href="#">Terms  </a></p>
    </footer>
</div>

expresstrade/templates/base/js.html
{% load static %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js"
        integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4"
        crossorigin="anonymous"></script>

expresstrade/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as products_list_url %}
{% url 'login' as login_url %}
{% url 'register' as register_url %}
{% url 'logout' as logout_url %}
{#navbar-light bg-light# - light colour #}
{# navbar-toggleable-md navbar-inverse fixed-top bg-inverse#}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3 fixed-top">
    <a class="navbar-brand" href="{{ home_url }}">
        {% if brand_name %}{{ brand_name }}{% else %}No Navbar Name{% endif %}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {# if link is active bold it #}
            <li class="nav-item {% if request.path == home_url %}active{% endif %}">
                <a class="nav-link" href="{{ home_url }}">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
                <a class="nav-link" href="{{ contact_url }}">Contact</a>
            </li>
            <li class="nav-item {% if request.path == products_list_url %}active{% endif %}">
                <a class="nav-link" href="{{ products_list_url }}">Products</a>
            </li>
            {% if request.user.is_authenticated %}
                <li class="nav-item {% if request.path == logout_url %}active{% endif %}">
                    <a class="nav-link" href="{{ logout_url }}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item {% if request.path == login_url %}active{% endif %}">
                    <a class="nav-link" href="{{ login_url }}">Login</a>
                </li>
                <li class="nav-item {% if request.path == register_url %}active{% endif %}">
                    <a class="nav-link" href="{{ register_url }}">Register</a>
                </li>
            {% endif %}

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
        </ul>
        {% include "search/snippets/search-form.html" %}
    </div>
</nav>